### ISSUE TITLE
[Pockets] Not Reflecting Enable/Disable State.

### ISSUE THREAD

**Issue by adrianspeyer** [vanilla/addons#464] opened 2017-03-05 23:19 UTC
Running version Version 2.4.100, on a self-hosted, using PHP 5.6 Apache.

The state for enable/disable of all pockets are not respected. All pockets are always enabled.

If I roll back 
https://github.com/vanilla/addons/commit/bfcbe515d4855edd19db6a59b7ec5c9926b952fd

works fine.

**Comment by adrianspeyer** [comment] 2017-05-12 13:14
Still an issue in Version 2.4.200

**Comment by Charrondev** [comment] 2017-05-30 20:23
Are any of these Pockets explicitly declared in the theme's view? Or are they just normally pockets for page locations?

**Comment by adrianspeyer** [comment] 2017-05-30 21:04
Both as far as I can tell

**Comment by adrianspeyer** [comment] 2017-12-01 03:00
Using Version 2.5a2. I am having an issue with the pockets plugin. When I try to select disable a pocket I get the confirmation via a growl, but then when I come back it does not keep the disabled state. Using php 7.1 on apache. I turn on debug and there is no error. Issue happens both in Chrome and Firefox.

**Comment by linc** [comment] 2017-12-01 15:41
Are any database updates pending?

Does the `Disabled` column toggle to `1` when this action is taken, or does it remain at zero?

Have you confirmed the `Disabled` column is currently at a valid value? (integer: `1`, `2`, or `0`).

**Comment by linc** [comment] 2017-12-01 15:42
My next debug step after this would be to physically delete Pockets from the file system, re-upload it, then refresh your cache.

**Comment by adrianspeyer** [comment] 2017-12-01 15:59
Disabled does get recorded in the DB, but is not reflected in dashboard or in the front end. I have deleted the Pockets from the file system, re-upload it, and refresh my cache. Still doing the same thing. 

Next step is to delete the table and start over.

**Comment by linc** [comment] 2017-12-01 16:10
If you have a good DB state, the next step is to pick apart how it's being read.

```
        if ($this->Disabled === Pocket::DISABLED) {
            return false;
        }
```

This is where it evaluates a disabled Pocket. Make sure it's getting **int** `1` for `$this->Disabled` at this check.

**Comment by Charrondev** [comment] 2017-12-01 16:16
I took a quick look and I can't see what's wrong at a glance. I'm unable to reproduce on my own Vanilla installation. My hunch is that this is related to some other plugin interfering.

Short summary:

- Vanilla version and Addon version are 2.5a2.
- Pockets being disable properly writes to the DB.
- This value is not properly read out and is not reflected in the frontend.
- Nothing in Vanilla's logs seems to relate to the Pockets Plugin
- There seems to be some kind of error related to the Pockets table in the shared hosting console, but it the message is truncated and you can't see the whole thing.
- MySQL and PHP logs don't seem to available in the environment.

One or all of the following would be useful
- PHP logs
- MySQL logs
- A list of any unofficial addons, and links to their source code.

Being able to reproduce the problem locally goes a long way in diagnosing this type of issue.

**Comment by adrianspeyer** [comment] 2017-12-01 16:46
@linc 

It's listed as 

`smallint(6)`

**Comment by adrianspeyer** [comment] 2017-12-01 18:31
- The error was me trying to repair the DB and it was not an available option. This was Not related to the plugin itself.
- I do have PHP & MySQL logs, but they do not indicate an issue.
- The item is written as `smallint(6)` in my DB. It is 100% recording changes in the DB for enabled and disabled, it's just not reflected in the UI or in the state of the Pocket itself. 

Weird that it cannot be replicated elsewhere. I'll continue to dig.

**Comment by linc** [comment] 2017-12-27 00:14
Closing until we have something reproducible.

**Closed by linc** 2017-12-27 00:14 UTC
