### ISSUE TITLE
Enhancement: Answer Own Question

### ISSUE THREAD

**Issue by adrianspeyer** [vanilla/addons#233] opened 2015-07-08 19:39 UTC
It would make sense for a way to allow members (without being a moderator) to accept their own answer, but without gaining a point.

http://vanillaforums.org/discussion/30351/answer-own-question

**Comment by linc** [comment] 2015-08-31 03:07
Duplicate of #67

**Closed by linc** 2015-08-31 03:07 UTC

**Comment by exitgames** [comment] 2015-08-31 10:25
Closing this means you will not add this?

**Comment by adrianspeyer** [comment] 2015-08-31 10:54
No. It was my fault for not finding that this had been requested earlier. As noted, it is under issue 67.
