### ISSUE TITLE
Civil Tongue does not work with Cyrillic letters

### ISSUE THREAD

**Issue by derrickeason** [vanilla/addons#338] opened 2016-05-26 16:26 UTC
This was first reported to us by EA on their international Battlefield forums. (cl531)

I've tested this and confirmed. I entered a Cyrillic word in the Civil tongue plugin settings and used that word in a few posts and it was not filtered out with **** as expected. 

I tested this here: http://juliemartin.vanillaforums.com/discussion/1874/testing-civil-tongue-with-cyrillic-letter#latest (cl311).

**Comment by linc** [comment] 2016-05-26 16:33
My off-the-cuff guess is that this is related to not using the 'u' modifier for `preg_replace()` in the `replace()` method. Whoever gets assigned to this I'd like to spend no more than an hour evaluating the feasibility of a fix here (finding a root cause). If it requires more than that to fix, let's talk quick before committing to more time.

**Comment by DaazKu** [comment] 2016-05-26 16:37
Copy paste this: `While at it, this will not work either: Ass`
 Reason: Nullbyte in the word.

**Closed** 2016-06-10 16:13 UTC
